import type { Metadata } from "next";
import ContentRoot from './ContentRoot';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContentRoot>{children}</ContentRoot>
      </body>
    </html>
  );
}
